jacocoTestReport {
	reports {
		html.required = true
		xml.required = true
	}

	dependsOn test

	// https://www.baeldung.com/jacoco-report-exclude#2-gradle-configuration
	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it, exclude: ['bio/terra/externalcreds/generated/**'])
		}))
	}
}

spotbugs {
	// using a classloader here is ugly, but is the consensus solution from
	// https://github.com/spotbugs/spotbugs-gradle-plugin/issues/972
	def classLoader = plugins["com.github.spotbugs"].class.classLoader
	def SpotBugsConfidence = classLoader.findLoadedClass("com.github.spotbugs.snom.Confidence")
	def SpotBugsEffort = classLoader.findLoadedClass("com.github.spotbugs.snom.Effort")

	reportLevel = SpotBugsConfidence.HIGH
	effort = SpotBugsEffort.MAX
	reportsDir = file("${project.reporting.baseDir}/spotbugs")
	excludeFilter = file('../common/spotbugsExclude.xml')
}

spotbugsMain {
	reports {
		sarif { enabled = true }
	}
}

spotbugsTest { enabled = false }
